services:
  - name: DiagramWeatherApp
    type: web
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    branch: main
    rootDir: .
    autoDeployTrigger: commit
